---
# File: dnsmasq.yml - Dnsmasq tasks for Consul

- name: Install Dnsmasq package
  apt:
    name: dnsmasq
    state: present
  when: ansible_os_family == "Debian"
  tags: dnsmasq, installation

- name: Enable dnsmasq service
  service:
    name: dnsmasq
    enabled: yes
  tags: dnsmasq

- name: Create Dnsmasq configuration
  template:
    src: dnsmasq-10-consul.j2
    dest: /etc/dnsmasq.d/10-consul
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
  when: ansible_os_family in ["Debian"]
  tags: dnsmasq
