---
# File: site.yml - Example Consul site playbook

- name: Assemble Consul cluster
  hosts: consul_instances
  any_errors_fatal: true
  become: yes
  become_user: root
  roles:
    - { role: ufw }
    - { role: consul }

- name: Assemble Consul cluster
  hosts: vaults
  any_errors_fatal: true
  become: yes
  become_user: root
  roles:
    - { role: docker }
    - { role: vault }
